In [1]:
# UNINASSAU
# DOCENTE: Cloves Rocha
# ESTUDANTES: ...
# 11. Um pouco de Álgebra Linear

# IMC
imc = [181, #altura
       100, #peso
        40] #idade
print(imc)

[181, 100, 40]


In [2]:
notas = [10, #nota1
          9, #nota2
          8, #nota3
          7] #nota4
print(notas)

[10, 9, 8, 7]


In [ ]:
def vetadd(vet1, vet2):
  #soma elementos correspondentes
return [vet1_i + vet2_i
        for vet1_i, vet2_i in zip(vet1, vet2)]

In [ ]:
def vetsub(vet1, vet2):
  #subtrai elementos correspondentes
return [vet1_i - vet2_i
        for vet1_i, vet2_i in zip(vet1, vet2)]


In [ ]:
def vet_sum(vets):
  return reduz(vet_add, vets)
vet_sum = part(reduz, vet_add)

In [ ]:
def scalar_mult(n, v):
  # n é um número, v é um vetor
return [n * v_i for v_i in v]

In [4]:
# Matrizes
import numpy as np #numpy é uma biblioteca importante

matriz = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
elemento = matriz[0,1]
#Obtém o elemento na linha 0 e coluna 1(valor2)
#Obtendo o número de linhas e colunas
num_linhas = matriz.shape[0] #Retorna o num de linhas(3)
num_colunas = matriz.shape[1] #Retorna o num de colunas(3)

#Iterando sobre elementos da matriz
for linha in matriz:
 for elemento in linha:
  print(elemento)

In [7]:
# Operações matriciais
matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])

soma = matriz1 + matriz2
produto = np.dot(matriz1, matriz2) #Produto de matrizes
print(soma)

[[ 6  8]
 [10 12]]


In [10]:
#matriz_transposta = matriz.exemplo
a = 1
b = 2
a = b
print(a)

2


In [11]:
# Indexação booleana
matriz = np.array([[1,2,3], [4,5,6], [7,8,9]])
condicao = matriz > 5
#Cria uma matriz de booleanos baseada na condição
elementos_maiores_que_5 = matriz [condicao]
#Obtém elementos maiores que 5.
#Outras operações úteis incluem: média, mínimo, máximo, etc.
media = np.mean(matriz)
valor_minimo = np.min(matriz)
valor_maximo = np.max(matriz)
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
